#!/usr/bin/env node
/**
 * Copia assets do repo pai (favicon + theme.css) para public/.
 * Executado automaticamente antes do build quando usado como submodulo.
 * Silencioso se o pai não existir (uso standalone).
 */

import { existsSync, copyFileSync, readdirSync, rmSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(rootDir, "public");
const parentDir = join(rootDir, "..");
const parentPublic = join(parentDir, "public");
const generatedBrandFile = join(rootDir, "src/generated/brand.ts");

if (!existsSync(parentPublic)) {
	// Standalone — sem pai, usa assets locais
	process.exit(0);
}

function escJs(str) {
	return String(str).replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function detectParentBrand() {
	const brandFile = join(parentPublic, "brand.txt");
	if (existsSync(brandFile)) {
		const raw = readFileSync(brandFile, "utf-8").trim();
		if (raw) return raw;
	}

	const parentIndex = join(parentDir, "src/pages/index.astro");
	if (existsSync(parentIndex)) {
		const source = readFileSync(parentIndex, "utf-8");
		const match = source.match(/<a[^>]*class=\"logo\"[^>]*>([^<]+)<span>([^<]*)<\/span>/i);
		if (match) return match[1].trim() + (match[2] || "").trim();
	}

	return "Quizzes";
}

const brand = detectParentBrand();
const brandSource =
	"// Auto-generated by scripts/copy-assets.js\n" +
	`export const BRAND = '${escJs(brand)}';\n`;
mkdirSync(dirname(generatedBrandFile), { recursive: true });
writeFileSync(generatedBrandFile, brandSource);

let copied = 0;
const parentFiles = readdirSync(parentPublic);

// Favicon
for (const f of parentFiles.filter((f) => f.startsWith("favicon"))) {
	copyFileSync(join(parentPublic, f), join(publicDir, f));
	copied++;
}

// Logo (opcional): qualquer ficheiro com prefixo logo.
for (const f of parentFiles.filter((f) => f.startsWith("logo"))) {
	copyFileSync(join(parentPublic, f), join(publicDir, f));
	copied++;
}

// theme.css — sobrescreve as CSS variables do quizzes com o tema do pai
if (existsSync(join(parentPublic, "theme.css"))) {
	copyFileSync(join(parentPublic, "theme.css"), join(publicDir, "theme.css"));
	copied++;
}

// Evita favicon antigo local quando o pai só fornece favicon.svg.
const parentIco = join(parentPublic, "favicon.ico");
const localIco = join(publicDir, "favicon.ico");
if (!existsSync(parentIco) && existsSync(localIco)) {
	rmSync(localIco);
}

// Evita logo antigo local quando o pai não fornece logo.
if (!parentFiles.some((f) => f.startsWith("logo"))) {
	for (const f of readdirSync(publicDir).filter((f) => f.startsWith("logo"))) {
		rmSync(join(publicDir, f));
	}
}

if (copied > 0) {
	console.log(`✓ ${copied} asset(s) copiado(s) do pai.`);
}
